openapi: "3.0.0"
info:
  title: Tshirt store API.
  description: A full fledged api for ecommerce store.
  version: 1.1.0
  contact:
    email: asho4@google.com
    url: "https://github.com/tripsterxx/Backend-development"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for local host - secure
#   - url: "http://localhost:4000/api/v1"
#     description: for local host - regular


servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host - secure
    variables:
      version:
        enum:
          - v1 
          - v2
        default: v1 
      protocol:
        enum:
          - https
          - http
        default: http 

components:
  securitySchemes: 
    cookieAuth:
      type: apiKey
      in: cookie 
      name: token 
    BearerAuth:
        type: http
        scheme: bearer

paths:
  /dummy: 
    get:
      tags:
        - Home 
      summary: returns a greet message from LCO.
      responses:
        200:
          description: All good and success. 
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request.
        500:
          description: Internal server error.